# Copyright (c) 2018 CA. All rights reserved.
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.

version: '3.4'
services:
  gateway-dev:
    hostname: dockgw.layer7.broadcom.com
    image: caapim/gateway:9.4.00
    ports:
    - "8082:8080"
    - "8444:8443"
    - "8000:8000"
    volumes:
    - /opt/SecureSpan/Gateway/node/default/etc/bootstrap/services/restman
    - ./deployment/build/gateway/deployment-1.0.0.gw7:/opt/docker/rc.d/deployment.gw7
    #- ./AWS-SK/src/main/gateway/config/global-env.properties:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/env/global-env.properties
    - ./Enterprise/src/main/gateway/config/global-env.properties:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/env/global-env.properties
    - ./Enterprise/src/main/gateway/config/privateKeys:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/env/config/privateKeys
    #- ./Enterprise/src/main/gateway/config/certificates:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/certificates
    secrets:
    - source: license
      target: /opt/SecureSpan/Gateway/node/default/etc/bootstrap/license/license.xml
    environment:
      ACCEPT_LICENSE: "true"
      SSG_ADMIN_USERNAME: "admin"
      SSG_ADMIN_PASSWORD: "7layer"
      ENV.PRIVATE_KEY.ssl: '{ "keystore": "Generic", "algorithm": "RSA", "keyPassword": "7layer" }'
      ENV.CERTIFICATE.star.layer7.broadcom.com.client: '{
                      "verifyHostname" : false,
                      "trustedForSsl" : true,
                      "trustedAsSamlAttestingEntity" : true,
                      "trustAnchor" : true,
                      "revocationCheckingEnabled" : true,
                      "trustedForSigningClientCerts" : true,
                      "trustedForSigningServerCerts" : true,
                      "trustedAsSamlIssuer" : true
                      }'
      ENV.CERTIFICATE_FILE.star.layer7.broadcom.com.client.pem: |-
                        Bag Attributes
                            friendlyName: ssl
                            localKeyID: 95 1F 81 A9 4F 78 E8 06 71 61 64 E9 88 D7 85 2C C7 27 8B D2 
                        subject=/OU=Domain Control Validated/OU=PositiveSSL Wildcard/CN=*.layer7.broadcom.com
                        issuer=/C=GB/ST=Greater Manchester/L=Salford/O=Sectigo Limited/CN=Sectigo RSA Domain Validation Secure Server CA
                        -----BEGIN CERTIFICATE-----
                        MIIGijCCBXKgAwIBAgIQPRVihgdAtQUBSY9qtzM+7zANBgkqhkiG9w0BAQsFADCB
                        jzELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4G
                        A1UEBxMHU2FsZm9yZDEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQD
                        Ey5TZWN0aWdvIFJTQSBEb21haW4gVmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENB
                        MB4XDTE5MTAxNzAwMDAwMFoXDTIxMTAxNjIzNTk1OVowYjEhMB8GA1UECxMYRG9t
                        YWluIENvbnRyb2wgVmFsaWRhdGVkMR0wGwYDVQQLExRQb3NpdGl2ZVNTTCBXaWxk
                        Y2FyZDEeMBwGA1UEAwwVKi5sYXllcjcuYnJvYWRjb20uY29tMIIBIjANBgkqhkiG
                        9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwtA1pn7rEjTQkzpk506jooVjDJZ/HoFS0e4j
                        SgN8UxwJw225PEvM04OfrxSO+wKzpsUKYD3RJ+awMFx+p7ufju/ixooyA6jjLdiX
                        n73Nznxt/1NEWSG+dnRKPHrTwZCFW3aV4AUYjVdGyzbSA0IrrxGcBgDcZSlrDYQq
                        RUPVT8pTYVZKs/F4TwTNelf2w2CjdUiTdFamRN1+VbQzpm3mZkgO5b2ENYW7+J72
                        PAQBvq+J2mjeD5pzQw5A3yTCXImxD/kkAO82MdLsH+c9oPXOrdBalEutIBj3YHYV
                        9Hkq9fDjCwXlNbr9NmT6sTYLp9+h0P7in47kCdozhNz5UPWqEwIDAQABo4IDDDCC
                        AwgwHwYDVR0jBBgwFoAUjYxexFStiuF36Zv5mwXhuAGNYeEwHQYDVR0OBBYEFDXK
                        kRTsmfk9GJl5rioEgT2BiupwMA4GA1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAA
                        MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBJBgNVHSAEQjBAMDQGCysG
                        AQQBsjEBAgIHMCUwIwYIKwYBBQUHAgEWF2h0dHBzOi8vc2VjdGlnby5jb20vQ1BT
                        MAgGBmeBDAECATCBhAYIKwYBBQUHAQEEeDB2ME8GCCsGAQUFBzAChkNodHRwOi8v
                        Y3J0LnNlY3RpZ28uY29tL1NlY3RpZ29SU0FEb21haW5WYWxpZGF0aW9uU2VjdXJl
                        U2VydmVyQ0EuY3J0MCMGCCsGAQUFBzABhhdodHRwOi8vb2NzcC5zZWN0aWdvLmNv
                        bTA1BgNVHREELjAsghUqLmxheWVyNy5icm9hZGNvbS5jb22CE2xheWVyNy5icm9h
                        ZGNvbS5jb20wggF+BgorBgEEAdZ5AgQCBIIBbgSCAWoBaAB2AH0+8viP/4hVaCTC
                        wMqeUol5K8UOeAl/LmqXaJl+IvDXAAABbdrXE58AAAQDAEcwRQIhAJy9guis7Nbt
                        66WRIoHQ0aaCoJZPMBfdgJoV2p8FDgR0AiAwg35EmytyEOkznytNOZX7lGv9jyXT
                        APaFtewWAMQHqgB3AESUZS6w7s6vxEAH2Kj+KMDa5oK+2MsxtT/TM5a1toGoAAAB
                        bdrXE5gAAAQDAEgwRgIhAOZcEkKMuVQzg8CX1t8QoxDjMXzNO75n/kLOX/AOC/G8
                        AiEAjZoUlwmHS2Zg62PTqKkW28sGCbMCy8+tqn1q70QpdDIAdQBVgdTCFpA2AUrq
                        C5tXPFPwwOQ4eHAlCBcvo6odBxPTDAAAAW3a1xPIAAAEAwBGMEQCIEgX+2gmXaHX
                        enK/lrcPg8bVMfnbfpngMs2NSyP3fXg1AiBlV9M2l9tgKKKNEuZzyJ5wbR/7Rv82
                        6oYDOtlXsVBlDjANBgkqhkiG9w0BAQsFAAOCAQEAxbyTfVkYBbAeh5J1rQuZWeG+
                        bk0cTPROJX3LvyahUHvznHiEKk74AyuqMMPrRo9ujC0hI+xQPTjzJqEUcTIhxT8r
                        oWNdOkUjrWYYIQfz6CgnWbOI9dfKEi5yma4ogBiNSysD4jTA0TVh7I7jzUMygWzE
                        nkxGzZAhgaaPLIKrJ3aLF4yD/Lg4bYalaFT6JwHcABma8PiGEzdlHLN+qhS27P61
                        Dm8owff1iEKbLdsUprI2HhpgLsQdw4ZWKBGvsPQYWEgEZYcSyACYghzPvblkIhCt
                        eeBSNXTXU5syKD8YsLmuWTzFRU0I0lBzkVkjkxX0E6x8Xdy1hou42ZEqfwN0OA==
                        -----END CERTIFICATE-----
secrets:
  license:
    file: ./docker/license.xml
