kevin/kevin1:
  url: "/kevin1"
  policy: "kevin/kevin1"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
  wssProcessingEnabled: false
kevin/folder1/kevin2:
  url: "/kevin2"
  policy: "kevin/folder1/kevin2"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
  wssProcessingEnabled: false
